--------------------------------------------------------
--  파일이 생성됨 - 목요일-1월-07-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GCOMMENT4
--------------------------------------------------------

  CREATE TABLE "BIT"."GCOMMENT4" 
   (	"GNO" NUMBER, 
	"GCNO" NUMBER, 
	"GCCONTENTS" VARCHAR2(1000 BYTE), 
	"GCWRITER" VARCHAR2(50 BYTE), 
	"GCDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into BIT.GCOMMENT4
SET DEFINE OFF;
Insert into BIT.GCOMMENT4 (GNO,GCNO,GCCONTENTS,GCWRITER,GCDATE) values (72,1,'이쁘네요 무슨꽃인가요?','js',to_date('21/01/03','RR/MM/DD'));
Insert into BIT.GCOMMENT4 (GNO,GCNO,GCCONTENTS,GCWRITER,GCDATE) values (72,2,'궁금해요ㅜ 보시면 답좀달아주세요~','js',to_date('21/01/03','RR/MM/DD'));
Insert into BIT.GCOMMENT4 (GNO,GCNO,GCCONTENTS,GCWRITER,GCDATE) values (72,3,'이쁘네요~','ldy',to_date('21/01/03','RR/MM/DD'));
Insert into BIT.GCOMMENT4 (GNO,GCNO,GCCONTENTS,GCWRITER,GCDATE) values (72,22,'저도 궁금해요~','ldy',to_date('21/01/03','RR/MM/DD'));
Insert into BIT.GCOMMENT4 (GNO,GCNO,GCCONTENTS,GCWRITER,GCDATE) values (66,21,'멋지네요~','js',to_date('21/01/04','RR/MM/DD'));
Insert into BIT.GCOMMENT4 (GNO,GCNO,GCCONTENTS,GCWRITER,GCDATE) values (61,22,'이쁘네요~~ 어디서 사셨어요??','ysy',to_date('21/01/04','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C007143
--------------------------------------------------------

  CREATE UNIQUE INDEX "BIT"."SYS_C007143" ON "BIT"."GCOMMENT4" ("GNO", "GCNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table GCOMMENT4
--------------------------------------------------------

  ALTER TABLE "BIT"."GCOMMENT4" MODIFY ("GNO" NOT NULL ENABLE);
  ALTER TABLE "BIT"."GCOMMENT4" MODIFY ("GCNO" NOT NULL ENABLE);
  ALTER TABLE "BIT"."GCOMMENT4" MODIFY ("GCCONTENTS" NOT NULL ENABLE);
  ALTER TABLE "BIT"."GCOMMENT4" MODIFY ("GCWRITER" NOT NULL ENABLE);
  ALTER TABLE "BIT"."GCOMMENT4" ADD PRIMARY KEY ("GNO", "GCNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
