--------------------------------------------------------
--  파일이 생성됨 - 목요일-1월-07-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GCOMMENT
--------------------------------------------------------

  CREATE TABLE "BIT"."GCOMMENT" 
   (	"GNO" NUMBER, 
	"GCNO" NUMBER, 
	"GCCONTENTS" VARCHAR2(1000 BYTE), 
	"GCWRITER" VARCHAR2(50 BYTE), 
	"GCDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into BIT.GCOMMENT
SET DEFINE OFF;
Insert into BIT.GCOMMENT (GNO,GCNO,GCCONTENTS,GCWRITER,GCDATE) values (2,3,'아마 3일?','테스티',to_date('20/12/22','RR/MM/DD'));
Insert into BIT.GCOMMENT (GNO,GCNO,GCCONTENTS,GCWRITER,GCDATE) values (2,4,'잘모르겠어요..','테이티',to_date('20/12/22','RR/MM/DD'));
Insert into BIT.GCOMMENT (GNO,GCNO,GCCONTENTS,GCWRITER,GCDATE) values (7408,261,'좋습니다~','js',to_date('21/01/04','RR/MM/DD'));
Insert into BIT.GCOMMENT (GNO,GCNO,GCCONTENTS,GCWRITER,GCDATE) values (7408,262,'좋은 정보 감사합니다~','test225',to_date('21/01/04','RR/MM/DD'));
Insert into BIT.GCOMMENT (GNO,GCNO,GCCONTENTS,GCWRITER,GCDATE) values (7387,264,'집 앞이네요 이뻐요!','js',to_date('21/01/05','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C007229
--------------------------------------------------------

  CREATE UNIQUE INDEX "BIT"."SYS_C007229" ON "BIT"."GCOMMENT" ("GNO", "GCNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table GCOMMENT
--------------------------------------------------------

  ALTER TABLE "BIT"."GCOMMENT" MODIFY ("GNO" NOT NULL ENABLE);
  ALTER TABLE "BIT"."GCOMMENT" MODIFY ("GCNO" NOT NULL ENABLE);
  ALTER TABLE "BIT"."GCOMMENT" MODIFY ("GCCONTENTS" NOT NULL ENABLE);
  ALTER TABLE "BIT"."GCOMMENT" MODIFY ("GCWRITER" NOT NULL ENABLE);
  ALTER TABLE "BIT"."GCOMMENT" ADD PRIMARY KEY ("GNO", "GCNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
